Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.hostname = ENV.fetch("VM_HOSTNAME", "web03")

  config.vm.network "private_network",
    ip: ENV.fetch("VM_IP", "192.168.56.14")

  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV.fetch("VM_HOSTNAME", "web03").capitalize
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell",
    inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      cat /vagrant/ansible-control.pub >> /home/vagrant/.ssh/authorized_keys

      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL

end