[control]
ansible-control ansible_connection=local

[production]
web01 ansible_host=192.168.56.11
web03 ansible_host=192.168.56.14 ansible_user=vagrant

[staging]
web02 ansible_host=192.168.56.12

[webservers:children]
production
staging

[database]
db01 ansible_host=192.168.56.13

[all:vars]
ansible_user=ubuntu