[control]
ansible-control ansible_connection=local

[production]
web01 ansible_host=192.168.56.10 ansible_user=vagrant
web03 ansible_host=192.168.56.12 ansible_user=vagrant


[staging]
web02 ansible_host=192.168.56.11 ansible_user=vagrant


[database]
db01 ansible_host=192.168.56.13 ansible_user=vagrant



[webservers:children]
production
staging