- name: Install useful tools on all servers
  hosts: all
  become: true

  tasks:
    - name: Install multiple packages using apt
      apt:
        name: 
          - tree
          - htop
          - curl
          - git
        state: present
        update_cache: yes

    #  second approach to install htop
    # - name: Install htop
    #   apt:
    #     name: htop
    #     state: present