---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
    - packages

- name: Install extra packages
  ansible.builtin.apt:
    name:
      - htop
      - curl
      - git
      - tree
      - mariadb-client
    state: present
    update_cache: true

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true
  tags: 
    - services

- name: Deploy custom homepage
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart nginx
  tags:
    - config


- name: Deploy database configuration
  template:
    src: database.conf.j2
    dest: /tmp/database.conf
  tags:
    - config