---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  when: ansible_facts["distribution"] == "Ubuntu"
  tags:
    - packages

- name: Install extra packages
  ansible.builtin.apt:
    name:
      - htop
      - curl
      - git
      - tree
      - mariadb-client
    state: present
    update_cache: true

- name: Ensure nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  tags: 
    - services

- name: Deploy custom homepage
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart nginx
  tags:
    - config


- name: Deploy database configuration
  template:
    src: database.conf.j2
    dest: /tmp/database.conf
  tags:
    - config

- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify:
    - Restart nginx

- name: Deploy dashboard reverse proxy
  ansible.builtin.template:
    src: dashboard.conf.j2
    dest: /etc/nginx/sites-available/dashboard
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - Restart nginx


- name: Enable dashboard reverse proxy
  ansible.builtin.file:
    src: /etc/nginx/sites-available/dashboard
    dest: /etc/nginx/sites-enabled/dashboard
    state: link
  become: true
  notify:
    - Restart nginx