Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "web03"

  config.vm.network "private_network",
    ip: "192.168.56.14"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Web03"
    vb.memory = 2048
    vb.cpus = 2
  end

end